### ISSUE TITLE
Blog Post on recent security incidents

### ISSUE THREAD

**Issue by xavier506** [edenia/tikuna#125]
A blog post describing the importance of cybersecurity monitoring for blockchain 
- [ ] Create a listing of security incidents that can be updated periodically, similar concept to [BTC obituaries ](https://99bitcoins.com/bitcoin-obituaries/) or [rekt](https://rekt.news/leaderboard/)

**Comment by btcurenas** [comment]
Update: We'd like to do a listing of security incidents just focused on the P2P Network inside Ethereum. 
Just a few + a brief description.
