### ISSUE TITLE
About Sakundi Text for readme

### ISSUE THREAD

**Issue by xavier506** [edenia/tikuna#2]
About text in English and Spanish

```Sakundi intends to provide security and privacy services for Blockchain networks and their different stakeholders. We plan to start by providing security monitoring solutions to identify relevant incidents using Artificial Intelligence approaches. By alerting the users or stopping the detected attacks, we aim to reduce the risk of critical incidents and increase the security of Blockchain networks, Dapps, and their used computing infrastructure. In future work, we would explore other services, such as automated smart contract audits.```

**Comment by xavier506** [comment]
website: https://sakundi.io ?

social media accounts:
- 
-

**Comment by xavier506** [comment]
@kuronosec  Please provide a logo for this page

**Comment by Alsardy** [comment]
Sakundi is a blockchain-based security solution that utilizes the power of artificial intelligence and automation. We offer Software-as-a-Service solutions to automatically monitor, detect, and visualize security incidents in Blockchain networks, decentralized applications (D-apps), and infrastructure. In addition, Sakundi's mission is to ensure the security of blockchains by developing solutions that are supported by scientific research and can be easily deployed via plug-and-play services. Our team is made up of specialists from all around the world that are expert in the fields of cybersecurity, blockchain, Fintech, and DeFi ecosystems.

Website: https://sakundi.io/ 
Linkedin: https://www.linkedin.com/company/sakundi/

**Comment by Alsardy** [comment]
@kuronosec Could you please review the about Sakundi text
